# @name ApproveContent
PUT http://localhost:3001/api/content/approve/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY5Mjk1MzksImlkIjoxMiwiaW5zdGFuY2VfaWQiOjMyLCJyb2xlIjoyfQ.92K7De0l684jttf5Va1WY_4XlECBoozDmwkL5lubaNc


### @name RejectContent
PUT http://localhost:3001/api/content/reject/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY5Mjk1MzksImlkIjoxMiwiaW5zdGFuY2VfaWQiOjMyLCJyb2xlIjoyfQ.92K7De0l684jttf5Va1WY_4XlECBoozDmwkL5lubaNc

{
  "id": 15
}

### Login admin
# @name LoginMAnagerContent
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "ddo@yahoo.com",
  "password": "12321"
}

### Login User
# @name LoginMAnagerContent
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "dewi.lestari@gmail.com",
  "password": "dewi12345"
}





### Get all contents
# @name GetAllContents
GET http://localhost:3001/api
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc5NzM5MTIsImlkIjoxLCJpbnN0YW5jZV9pZCI6MSwicGVybWlzc2lvbnMiOlsidmlld19jb250ZW50cyIsInZpZXdfZHJhZnRzIiwic2VhcmNoX2NvbnRlbnRzIiwidmlld19jb250ZW50IiwiZWRpdF9jb250ZW50IiwiY3JlYXRlX2NvbnRlbnQiLCJjcmVhdGVfc3ViaGVhZGluZyIsImRlbGV0ZV9zdWJoZWFkaW5nIiwiZGVsZXRlX2NvbnRlbnQiLCJ2aWV3X3VzZXJfY29udGVudHMiLCJ2aWV3X2luc3RhbmNlcyIsInZpZXdfdXNlciIsInZpZXdfYWxsX3VzZXJzIiwidmlld19yb2xlcyIsImNyZWF0ZV91c2VyIiwiZWRpdF91c2VyIiwiZGVsZXRlX3VzZXIiLCJhZGRfaGlzdG9yeSIsInZpZXdfaGlzdG9yeV91c2VyIiwidmlld19sYXRlc3RfZWRpdG9yIiwiYXBwcm92ZV9jb250ZW50IiwicmVqZWN0X2NvbnRlbnQiLCJtYW5hZ2Vfcm9sZSIsInZpZXdfYWN0aXZlX2NvbnRlbnQiLCJ2aWV3X3Blcm1pc3Npb24iXSwicm9sZSI6IlN1cGVyIEFkbWluIiwicm9sZV9pZCI6NX0.hZpNB36RHQnJTZo8PzwrxSQPuoal9k78SS420QJa6hY
Accept: application/json

### Get all contents
# @name GetAllContents
GET http://localhost:3001/api/active
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2OTI3ODMsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.5XUnZ9jOlcWVAJG2mS5ZGVf-iSTIL4Kx_MmPD2HLaVs
Accept: application/json

###

### Search content
# @name SearchContent
GET http://localhost:3001/api/content?q=Holaku
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2OTI3ODMsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.5XUnZ9jOlcWVAJG2mS5ZGVf-iSTIL4Kx_MmPD2HLaVs
Accept: application/json

###

### Get content by ID
# @name GetContentByID
GET http://localhost:3001/api/content/76
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc5ODkzOTQsImlkIjo3LCJpbnN0YW5jZV9pZCI6MTksInBlcm1pc3Npb25zIjpbInZpZXdfY29udGVudHMiLCJ2aWV3X2RyYWZ0cyIsInNlYXJjaF9jb250ZW50cyIsInZpZXdfY29udGVudCIsImVkaXRfY29udGVudCIsImNyZWF0ZV9jb250ZW50IiwiY3JlYXRlX3N1YmhlYWRpbmciLCJkZWxldGVfc3ViaGVhZGluZyIsImRlbGV0ZV9jb250ZW50Iiwidmlld191c2VyX2NvbnRlbnRzIiwidmlld19pbnN0YW5jZXMiLCJ2aWV3X3VzZXIiLCJ2aWV3X2FsbF91c2VycyIsInZpZXdfcm9sZXMiLCJjcmVhdGVfdXNlciIsImVkaXRfdXNlciIsImRlbGV0ZV91c2VyIiwiYWRkX2hpc3RvcnkiLCJ2aWV3X2hpc3RvcnlfdXNlciIsInZpZXdfbGF0ZXN0X2VkaXRvciIsImFwcHJvdmVfY29udGVudCIsInJlamVjdF9jb250ZW50IiwibWFuYWdlX3JvbGUiLCJ2aWV3X2FjdGl2ZV9jb250ZW50Iiwidmlld19wZXJtaXNzaW9uIl0sInJvbGUiOiJBZG1pbiIsInJvbGVfaWQiOjF9.n3bv-lL2f_aqE_lPc326DNZenCSu_3WeDj_JLpTnBTM
Accept: application/json

###

### Edit content by ID
# @name EditContentByID
PUT http://localhost:3001/api/content/edit/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2OTI3ODMsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.5XUnZ9jOlcWVAJG2mS5ZGVf-iSTIL4Kx_MmPD2HLaVs
Content-Type: application/json

{
  "title": "Holaku",
  "description": "Updated bang",
  "instance_id": 1,
  "tag": "Updated, Tag Example",
  "subheadings": [
  ]
}


###

### Add new content
# @name AddContent
POST http://localhost:3001/api/content/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MzM4MDUsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.DaUismXwfZ_NEijqy_puGwfesGmVqzJU8iHgqhCOppQ

{
    "title": "kocak",
    "tag": "example_tag",
    "author_id": 2,
    "instance_id": 2

}

### Login User
# @name LoginUser
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "user"
}







###

### Add subheading
# @name AddSubheading
POST http://localhost:3001/api/subheading/add/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2OTY0OTYsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.CS2JNYKXdTgeN0vVi6yW5bvgi7MYrcigeFcLOhe0SkI
Content-Type: application/json

{
  "content_id": 3,
  "subheading": "hola",
  "subheading_description": "This is the description for the new subheading.",
  "author_id": 2,
  "created_at": "2025-01-10T10:00:00Z",
  "updated_at": "2025-01-10T10:00:00Z"
}


###

### Delete subheading by ID
# @name DeleteSubheading
DELETE http://localhost:3001/api/subheading/delete/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY2OTY0OTYsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.CS2JNYKXdTgeN0vVi6yW5bvgi7MYrcigeFcLOhe0SkI
Accept: application/json

###

### Login Admin
# @name LoginAdmin
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "password"
}
### Login User
# @name LoginUser
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "user@gmail.com",
  "password": "user"
}

###

### Delete content by ID
# @name DeleteContent
PUT http://localhost:3001/api/content/delete/65
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1MTc1NTIsImlkIjo3LCJpbnN0YW5jZV9pZCI6MTksInJvbGUiOjF9.JoG81Jbfl75JazPNGV8dRyf9uWCXH52CRaY1irklRyM
Accept: application/json

###

### Get all instances
# @name GetInstances
GET http://localhost:3001/api/instances
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MDEwNTcsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.npTfzNFvSQ0plNMmWF3Nezv-KkK92ymzt_r7igtY9mU
Accept: application/json

###

### Get user by ID
# @name GetUserByID
GET http://localhost:3001/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MDEwNTcsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.npTfzNFvSQ0plNMmWF3Nezv-KkK92ymzt_r7igtY9mU
Accept: application/json
###

### Get all users
# @name GetAllUsers
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MDEwNTcsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.npTfzNFvSQ0plNMmWF3Nezv-KkK92ymzt_r7igtY9mU
Accept: application/json

###

### Get roles
# @name GetRoles
GET http://localhost:3001/api/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc0MzcwNjMsImlkIjo3LCJpbnN0YW5jZV9pZCI6MTksInJvbGUiOjF9.xAdAtnfw-kgJMIC7Y6pBncVVy_2D8x_8o87Q3PDd70c
Accept: application/json

###

### Create new user
# @name CreateUser
POST http://localhost:3001/api/createuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MDEwNTcsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.npTfzNFvSQ0plNMmWF3Nezv-KkK92ymzt_r7igtY9mU
Content-Type: application/json

{
  "name": "yoi man",
  "email": "yoiman@gmail.com",
  "password": "coba",
  "role_id": 2,
  "instance_id": 1,
  "nip": 12345
}

###

### Edit user by ID
# @name EditUserByID
PUT http://localhost:3001/api/user/edit/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MDEwNTcsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.npTfzNFvSQ0plNMmWF3Nezv-KkK92ymzt_r7igtY9mU
Content-Type: application/json

{
  "name": "zzzUciha User",
  "email": "userzzz@example.com",
  "password": "securepassword",
  "role_id": 2,
  "instance_id": 1,
  "nip": 12345
}
###

### Delete user by ID
# @name DeleteUser
DELETE http://localhost:3001/api/user/8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzY3MDEwNTcsImlkIjoyLCJpbnN0YW5jZV9pZCI6Miwicm9sZSI6Mn0.npTfzNFvSQ0plNMmWF3Nezv-KkK92ymzt_r7igtY9mU
Accept: application/json

###

### Add history
# @name AddHistory
POST http://localhost:3001/api/history/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc0Mzc4NTAsImlkIjo3LCJpbnN0YW5jZV9pZCI6MTksInJvbGUiOjF9.nEXltufrVBlY2gozJrVV5KdclZfQ8ZuUlvIzHoDIlAo

{
  "content_id": 54,
  "editor_id": 7,
  "edited_at": "2025-01-16 12:00:00",
  "action": "Rejecting"
}


###

### Get user history by ID
# @name GetUserHistoryByID
GET http://localhost:3001/api/history/user/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzcyODM2NTQsImlkIjo3LCJpbnN0YW5jZV9pZCI6MTksInJvbGUiOjF9.S942emhaR5zxTAVuDgwaZxx9of12qW3ZHNIk-QQdFDM
Accept: application/json

###

### Get latest editor name by content ID
# @name GetLatestEditorName
GET http://localhost:3001/api/latest-editor-name/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzcyODM2NTQsImlkIjo3LCJpbnN0YW5jZV9pZCI6MTksInJvbGUiOjF9.S942emhaR5zxTAVuDgwaZxx9of12qW3ZHNIk-QQdFDM
Accept: application/json

###

### Get contents by user ID
# @name GetContentsByUserID
GET http://localhost:3001/api/contents/user/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1Mzc5ODYsImlkIjo3LCJpbnN0YW5jZV9pZCI6MTksInJvbGUiOjF9.7gyETfmo6eA3XcY1wDTU3vWW17b2-4m-1bp_Rd08LBE
Accept: application/json

### permission
# @name DeleteUser
GET http://localhost:3001/api/permissions 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc2OTQ4NzUsImlkIjoxLCJpbnN0YW5jZV9pZCI6MSwicGVybWlzc2lvbnMiOlsidmlld19jb250ZW50cyIsInZpZXdfZHJhZnRzIiwic2VhcmNoX2NvbnRlbnRzIiwidmlld19jb250ZW50IiwiZWRpdF9jb250ZW50IiwiY3JlYXRlX2NvbnRlbnQiLCJjcmVhdGVfc3ViaGVhZGluZyIsImRlbGV0ZV9zdWJoZWFkaW5nIiwiZGVsZXRlX2NvbnRlbnQiLCJ2aWV3X3VzZXJfY29udGVudHMiLCJ2aWV3X2luc3RhbmNlcyIsInZpZXdfdXNlciIsInZpZXdfYWxsX3VzZXJzIiwidmlld19yb2xlcyIsImNyZWF0ZV91c2VyIiwiZWRpdF91c2VyIiwiZGVsZXRlX3VzZXIiLCJhZGRfaGlzdG9yeSIsInZpZXdfaGlzdG9yeV91c2VyIiwidmlld19sYXRlc3RfZWRpdG9yIiwiYXBwcm92ZV9jb250ZW50IiwicmVqZWN0X2NvbnRlbnQiLCJtYW5hZ2Vfcm9sZSIsInZpZXdfYWN0aXZlX2NvbnRlbnQiXSwicm9sZSI6IlN1cGVyIEFkbWluIiwicm9sZV9pZCI6NX0.axvrbXGFcwInRsPDAMIzTgD9lNP3DmbYW4yTWE7Z4WY
Accept: application/json


### Login SUPERadmin
# @name LoginMAnagerContent
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "email": "super@gmail.com",
  "password": "superadmin"
}


### permissionByRole
# @name DeleteUser
GET http://localhost:3001/api/permissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc3MDQ3NTYsImlkIjoxLCJpbnN0YW5jZV9pZCI6MSwicGVybWlzc2lvbnMiOlsidmlld19jb250ZW50cyIsInZpZXdfZHJhZnRzIiwic2VhcmNoX2NvbnRlbnRzIiwidmlld19jb250ZW50IiwiZWRpdF9jb250ZW50IiwiY3JlYXRlX2NvbnRlbnQiLCJjcmVhdGVfc3ViaGVhZGluZyIsImRlbGV0ZV9zdWJoZWFkaW5nIiwiZGVsZXRlX2NvbnRlbnQiLCJ2aWV3X3VzZXJfY29udGVudHMiLCJ2aWV3X2luc3RhbmNlcyIsInZpZXdfdXNlciIsInZpZXdfYWxsX3VzZXJzIiwidmlld19yb2xlcyIsImNyZWF0ZV91c2VyIiwiZWRpdF91c2VyIiwiZGVsZXRlX3VzZXIiLCJhZGRfaGlzdG9yeSIsInZpZXdfaGlzdG9yeV91c2VyIiwidmlld19sYXRlc3RfZWRpdG9yIiwiYXBwcm92ZV9jb250ZW50IiwicmVqZWN0X2NvbnRlbnQiLCJtYW5hZ2Vfcm9sZSIsInZpZXdfYWN0aXZlX2NvbnRlbnQiLCJ2aWV3X3Blcm1pc3Npb24iXSwicm9sZSI6IlN1cGVyIEFkbWluIiwicm9sZV9pZCI6NX0.ca2LGre0dG1NPCoM6rOoMnRFO62Qkvvr8fyH8A9I9RI
Accept: application/json

### permissionByRole
# @name DeleteUser
GET http://localhost:3001/api/role_permissions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc5NzUxMTEsImlkIjoxLCJpbnN0YW5jZV9pZCI6MSwicGVybWlzc2lvbnMiOlsidmlld19jb250ZW50cyIsInZpZXdfZHJhZnRzIiwic2VhcmNoX2NvbnRlbnRzIiwidmlld19jb250ZW50IiwiZWRpdF9jb250ZW50IiwiY3JlYXRlX2NvbnRlbnQiLCJjcmVhdGVfc3ViaGVhZGluZyIsImRlbGV0ZV9zdWJoZWFkaW5nIiwiZGVsZXRlX2NvbnRlbnQiLCJ2aWV3X3VzZXJfY29udGVudHMiLCJ2aWV3X2luc3RhbmNlcyIsInZpZXdfdXNlciIsInZpZXdfYWxsX3VzZXJzIiwidmlld19yb2xlcyIsImNyZWF0ZV91c2VyIiwiZWRpdF91c2VyIiwiZGVsZXRlX3VzZXIiLCJhZGRfaGlzdG9yeSIsInZpZXdfaGlzdG9yeV91c2VyIiwidmlld19sYXRlc3RfZWRpdG9yIiwiYXBwcm92ZV9jb250ZW50IiwicmVqZWN0X2NvbnRlbnQiLCJtYW5hZ2Vfcm9sZSIsInZpZXdfYWN0aXZlX2NvbnRlbnQiLCJ2aWV3X3Blcm1pc3Npb24iXSwicm9sZSI6IlN1cGVyIEFkbWluIiwicm9sZV9pZCI6NX0.r4gpr72w5AAEHGhDQhJlhnWNXFORjdXI4PZzZA8nTTQ
Accept: application/json


### GET ROLES
# @name GetROles
GET http://localhost:3000/api/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc5NzU2NzcsImlkIjoxLCJpbnN0YW5jZV9pZCI6MSwicGVybWlzc2lvbnMiOlsidmlld19jb250ZW50cyIsInZpZXdfZHJhZnRzIiwic2VhcmNoX2NvbnRlbnRzIiwidmlld19jb250ZW50IiwiZWRpdF9jb250ZW50IiwiY3JlYXRlX2NvbnRlbnQiLCJjcmVhdGVfc3ViaGVhZGluZyIsImRlbGV0ZV9zdWJoZWFkaW5nIiwiZGVsZXRlX2NvbnRlbnQiLCJ2aWV3X3VzZXJfY29udGVudHMiLCJ2aWV3X2luc3RhbmNlcyIsInZpZXdfdXNlciIsInZpZXdfYWxsX3VzZXJzIiwidmlld19yb2xlcyIsImNyZWF0ZV91c2VyIiwiZWRpdF91c2VyIiwiZGVsZXRlX3VzZXIiLCJhZGRfaGlzdG9yeSIsInZpZXdfaGlzdG9yeV91c2VyIiwidmlld19sYXRlc3RfZWRpdG9yIiwiYXBwcm92ZV9jb250ZW50IiwicmVqZWN0X2NvbnRlbnQiLCJtYW5hZ2Vfcm9sZSIsInZpZXdfYWN0aXZlX2NvbnRlbnQiLCJ2aWV3X3Blcm1pc3Npb24iXSwicm9sZSI6IlN1cGVyIEFkbWluIiwicm9sZV9pZCI6NX0.a9B8Rc8GkJjAb0OSdEupD9By5Vf5PVINtScDwEWoCkU
Accept: application/json